config/routes.rb
Takeout::Application.routes.draw do
	resources :pages

	resources :orders

	resources :menus

	match '/users/login' => 'users#login'
	match '/users/signin' => 'users#signin'
	match '/users/signout' => 'users#signout'
	match '/admin' => 'users#resetadmin'
	resources :users

	root :to => 'welcome#index'

	get "dashboard/index"

end

app/models/menu.rb
# coding utf-8
class Menu < ActiveRecord::Base
	attr_accessible :description, :name, :photo, :price
	has_attached_file :photo, :styles => { :medium => "260x180>", :thumb => "64x64>" }
	validates_uniqueness_of :name
end

app/controllers/menus_controller.rb
# coding: utf-8
class MenusController < ApplicationController
	respond_to :html, :json
	before_filter :admin

	def index
		@menus = Menu.order('id desc')
		
	end

	def show
		@menu = Menu.find(params[:id])
	end

	def new
		@menu = Menu.new
	end

	def edit
		@menu = Menu.find(params[:id])
	end

	def create
		@menu = Menu.new(params[:menu])
		if @menu.save
			flash[:notice] = '菜单成功创建了！' 
		end
		respond_with @menu
	end

	def update
		@menu = Menu.find(params[:id])
		if @menu.update_attributes(params[:menu])
			flash[:notice] = '菜单成功修改了！' 
			redirect_to menus_path
		end
	end

	def destroy
		@menu = Menu.find(params[:id])
		if @menu.destroy
			
		end
		respond_with @menu
	end

end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<% title("#{controller.action_name.capitalize} menu") %>

<%= error_messages_for(@menu) %>

<%= form_for(@menu, :html => { :class => 'form-horizontal', :multipart => true }) do |f| %>
	<fieldset>

		<div class="control-group">
			<%= f.label '菜名', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_field :name, :class => 'span7' %>
			</div>
		</div>

		<div class="control-group">
			<%= f.label '简介', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_field :description, :class => 'span7' %>
			</div>
		</div>

		<div class="control-group">
			<%= f.label '价格', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_field :price, :class => 'span7' %>
			</div>
		</div>

		<div class="control-group">
			<%= f.label '照片', :class => 'control-label' %>
			<div class="controls">
				<%= f.file_field :photo, :class => '' %>
			</div>
		</div>
		
		<div class="form-actions">
			<%= button_tag(nil, :class => "btn btn-primary") do |b| %>
				<i class="icon-ok icon-white"></i> 提交
			<% end %> or
			<%= link_to '取消', menus_path, :class => 'btn' %>
		</div>
	</fieldset>
<% end %>

app/views/menus/edit.html.erb
<%= render :partial => 'form' %>

app/views/menus/index.html.erb
<% title("Menus") %>
<p>
	<%= link_to(new_menu_path, :class => 'btn btn-success') do %>
		<i class="icon-plus icon-white"></i> 新菜单
	<% end %>
</p>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>

			<th>Name</th>

			<th>Created at</th>
			<th class="actions">Actions</th>
		</tr>
	</thead>
	<tbody>
		<%= content_tag_for(:tr, @menus) do |menu| %>
			<td>#<%= menu.id %></td>

			<td><strong><%= link_to("#{menu.name}", menu) %></strong></td>
			
			<td><%= menu.created_at %></td>
			<td class="actions">
				<%= link_to(edit_menu_path(menu), :class => 'btn btn-mini btn-primary') do %>
					<i class="icon-edit icon-white"></i> 编辑
				<% end %>
				<%= link_to(menu, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger') do %>
				 <i class="icon-remove icon-white"></i> 删除
				<% end %>
			</td>
		<% end %>
	 </tbody>
</table>

app/views/menus/new.html.erb
<%= render :partial => 'form' %>

app/views/menus/show.html.erb
<% title "菜式 ##{@menu.id}" %>

<table class="table table-bordered">
	<tbody>

		<tr><th><strong>名称</strong></th><td><%= @menu.name %></td></tr>
		
		<tr><th><strong>说明</strong></th><td><%= @menu.description %></td></tr>

		<tr><th><strong>说明</strong></th><td>￥<%= @menu.price %>元</td></tr>
		
		<tr><th><strong>照片</strong></th><td><%= image_tag @menu.photo.url %></td></tr>
		
	</tbody>
</table>

<div class="form-actions">
	<%= link_to(menus_path, :class => 'btn') do %>
		<i class="icon-circle-arrow-left"></i> Back
	<% end %> or 
	<%= link_to(edit_menu_path(@menu), :class => 'btn btn-primary') do %>
		<i class="icon-edit icon-white"></i> 编辑
	<% end %> 
	<%= link_to(@menu, :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger') do %>
		<i class="icon-remove icon-white"></i> 删除
	<% end %>
</div>