config/routes.rb
Takeout::Application.routes.draw do
	resources :pages

	resources :orders

	resources :menus

	match '/users/login' => 'users#login'
	match '/users/signin' => 'users#signin'
	match '/users/signout' => 'users#signout'
	match '/admin' => 'users#resetadmin'
	resources :users

	root :to => 'welcome#index'

	get "dashboard/index"

end

app/models/order.rb
# coding utf-8
class Order < ActiveRecord::Base
	attr_accessible :items, :prices, :tel, :user_name, :address
	validates_presence_of :items, :prices, :tel, :user_name, :address
	belongs_to :user
end

app/controllers/orders_controller.rb
# coding: utf-8
class OrdersController < ApplicationController
	respond_to :html, :json
	before_filter :auth

	def index
		if @admin
			@orders = Order.order('id desc').page(params[:page]).per(500)
		else
			@orders = Order.where("user_id = ?", @current_user.id).order('id desc')
		end

		@orders.each do |order|
			order.items = order.items.split(',').uniq.join(',')
		end
		respond_with(@orders)
	end

	def show
		@order = Order.find(params[:id])
		@items_arr = @order.items.split(',')
		@prices_arr = @order.prices.split(',')

		# Get items_arr_with_prices
		@items_arr_with_prices = []
		@items_arr.each_with_index { |e,i| @items_arr_with_prices.push(e + ':￥' + @prices_arr[i])}

		 # weird emuration to get occurences in an array
		@items_arr_with_prices_counts = @items_arr_with_prices.chunk{|y| y}.map{|y, ys| [y, ys.length]}

		@sum = @prices_arr.map { |e| e.to_f }.inject(:+)
	end

	def new
		@order = Order.new
		respond_with(@order)
	end

	def edit
		if @admin
			@order = Order.find(params[:id])
		else
			redirect_to '/pages/1'	
		end
	end

	def create
		if @current_user
			@order = Order.new(params[:order])
			@order.user = @current_user
			@order.tel = @current_user.tel
			@order.address = @current_user.address
			@order.user_name = @current_user.name
			@items_arr = @order.items.split(',')
			@prices_arr = []
			@items_arr.map { |e| @prices_arr.push(Menu.find_by_name(e).price) }
			@order.prices = @prices_arr.join(',')
			result = @order.save
		end

		if result
			path = order_path(@order)
			flash[:notice] = '恭喜您成功订餐，坐等美味自动送上门来吧！' 
			cookies.delete :_items
		else
			path = '/users/login'
		end
		redirect_to path
	end

	def update
		@order = Order.find(params[:id])
		flash[:notice] = '订单已经成功修改！' if @order.update_attributes(params[:order])
		respond_with(@order)
	end

	def destroy
		if @admin
			@order = Order.find(params[:id])
			@order.destroy
		else
			redirect_to '/pages/1'	
		end
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<% title("#{controller.action_name.capitalize} order") %>

<%= error_messages_for(@order) %>

<%= form_for(@order, :html => { :class => 'form-horizontal' }) do |f| %>
  <fieldset>

    <div class="control-group">
      <%= f.label :tel, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :tel, :class => 'span7' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :items, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :items, :class => 'span7' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :prices, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :prices, :class => 'span7' %>
      </div>
    </div>
    
    <div class="form-actions">
      <%= button_tag(nil, :class => "btn btn-primary") do |b| %>
        <i class="icon-ok icon-white"></i> Save
      <% end %> or
      <%= link_to 'Cancel', orders_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/orders/edit.html.erb
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<% title("Orders") %>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>顾客称呼</th>
			<th>菜单</th>
			<th>下单时间</th>
			<th class="actions"></th>
		</tr>
	</thead>
	<tbody>
		<%= content_tag_for(:tr, @orders) do |order| %>
			<td>#<%= order.id %></td>
			<td><strong><%= link_to("#{order.user_name}", order) %></strong></td>
			<td><strong><%= link_to order.items, order %></strong></td>
			<td><%= order.created_at.to_s(:db) %></td>
			
			<td class="actions">
				<% if @admin %>
					<%= link_to(edit_order_path(order), :class => 'btn btn-mini') do %>
						<i class="icon-edit icon-white"></i> 修改
					<% end %>
					<%= link_to(order, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger') do %>
					 <i class="icon-remove icon-white"></i> 删除
				<% end %>
				<% else %>
					<%= link_to(page_path(1), :class => 'btn btn-mini' ) do %>
						<i class="icon-edit icon-white"></i> 修改
					<% end %>
					<%= link_to(order, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger') do %>
					 <i class="icon-remove icon-white"></i> 删除
					<% end %>
				<% end %>
			</td>
		<% end %>
	 </tbody>
</table>

<%= paginate @orders %>

app/views/orders/new.html.erb
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<% title "Order ##{@order.id}" %>

<table class="table table-bordered">
	<tbody>

		<tr><th><strong>客户</strong></th><td><%= @order.user_name %></td></tr>
		
		<tr><th><strong>手机</strong></th><td><%= @order.tel %></td></tr>
		
		<tr><th><strong>订单</strong></th>
			<td>
				<% @items_arr_with_prices_counts.each_with_index do |item, index| %>
					<%=raw "#{item[0]} <span class='badge'>X #{item[1]}</span><br />" %>
				<% end %>
				<%= "合计: #{@sum} 元" %>
			</td>
		</tr>
		
	</tbody>
</table>

<div class="form-actions">
	<% if @admin %>
		<%= link_to(edit_order_path(@order), :class => 'btn btn-primary') do %>
			<i class="icon-edit icon-white"></i> 编辑
		<% end %> 
		<%= link_to(@order, :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger') do %>
			<i class="icon-remove icon-white"></i> 删除
		<% end %>
	<% end %>
</div>