config/routes.rb
Takeout::Application.routes.draw do
	resources :pages

	resources :orders

	resources :menus

	match '/users/login' => 'users#login'
	match '/users/signin' => 'users#signin'
	match '/users/signout' => 'users#signout'
	match '/admin' => 'users#resetadmin'
	resources :users

	root :to => 'welcome#index'

	get "dashboard/index"

end

app/views/pages/_form.html.erb
<% title("#{controller.action_name.capitalize} page") %>

<%= error_messages_for(@page) %>

<%= form_for(@page, :html => { :class => 'form-horizontal' }) do |f| %>
  <fieldset>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'span7' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :text, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :text, :class => 'span7' %>
      </div>
    </div>
    
    <div class="form-actions">
      <%= button_tag(nil, :class => "btn btn-primary") do |b| %>
        <i class="icon-ok icon-white"></i> Save
      <% end %> or
      <%= link_to 'Cancel', pages_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/pages/edit.html.erb
<%= render :partial => 'form' %>

app/views/pages/index.html.erb
<% title("Pages") %>
<p>
  <%= link_to(new_page_path, :class => 'btn btn-success') do %>
    <i class="icon-plus icon-white"></i> 新页面
  <% end %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>

      <th>Title</th>

      <th>Created at</th>
      <th class="actions">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= content_tag_for(:tr, @pages) do |page| %>
      <td>#<%= page.id %></td>

      <td><strong><%= link_to("#{page.title}", page) %></strong></td>
      
      <td><%= page.created_at %></td>
      <td class="actions">
        <%= link_to(edit_page_path(page), :class => 'btn btn-mini btn-primary') do %>
          <i class="icon-edit icon-white"></i> 编辑
        <% end %>
        <%= link_to(page, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger') do %>
         <i class="icon-remove icon-white"></i> 删除
        <% end %>
      </td>
    <% end %>
   </tbody>
</table>

app/views/pages/new.html.erb
<%= render :partial => 'form' %>

app/views/pages/show.html.erb
<% title @page.title %>

<%=raw @page.text %>

<% if @current_user == 'admin' %>
	<div class="form-actions">
		<%= link_to(pages_path, :class => 'btn') do %>
			<i class="icon-circle-arrow-left"></i> Back
		<% end %> or 
		<%= link_to(edit_page_path(@page), :class => 'btn btn-primary') do %>
			<i class="icon-edit icon-white"></i> 编辑
		<% end %> 
		<%= link_to(@page, :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger') do %>
			<i class="icon-remove icon-white"></i> 删除
		<% end %>
	</div>
<% end %>