config/routes.rb
Takeout::Application.routes.draw do
	resources :pages

	resources :orders

	resources :menus

	match '/users/login' => 'users#login'
	match '/users/signin' => 'users#signin'
	match '/users/signout' => 'users#signout'
	match '/admin' => 'users#resetadmin'
	resources :users

	root :to => 'welcome#index'

	get "dashboard/index"

end

app/helpers/layout_helper.rb
# coding: utf-8

# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title
    @show_title
  end

  def stylesheet(*args)
    content_for(:stylesheet) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:javascript) { javascript_include_tag(*args) }
  end

  def menu(name, path)
    content_tag(:li, link_to(name, path), :class => "#{'active' if request.path.gsub(/(.[^\/]+|\/)/).first == path}")
  end

  def analytics(site_id)
    html = <<-ANALYTICS
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{site_id}']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    ANALYTICS

    html.html_safe if Rails.env.production?
  end

  def app_name
    # Rails.application.class.to_s.split("::").first
    '外婆家'
  end
end

app/views/layouts/_navbar.html.erb
<div class="nav-collapse">
	<ul class="nav">
		<%= menu('首页', root_path) %>
		<%= menu('订单', orders_path) %>
		<%= menu('菜单', menus_path) if @admin %>
		<%= menu('用户', users_path) if @admin %>
		<%= menu('页面', pages_path) if @admin %>
	</ul>
</div>

app/views/layouts/_order_form.html.erb
	<%= form_for @order do |f| -%>
		<!-- Showcase page elements -->
		<ul class="nav nav-list">
			<li class="nav-header"><h4><i class="icon-check"></i>我的订单</h4></li>
			<li id="cart">
				<!-- Append cart items here -->
				<div class="cearfix"></div>
			</li>
			<li class="cart-actions "><div id="confirm-buy" class="btn btn-success btn-small"><i class="icon-legal"></i>下单</div><div id="reset" class="btn btn-small"><i class="icon-trash"></i>清空</div></li>
		  
		  <!-- Actual form elements -->
		  <%= f.hidden_field :tel %>
		  <%= f.hidden_field :items %>
		  
		  <!-- submit will perform by js on button -->
		</ul>
	<% end -%>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
	<%= render 'layouts/order_form' if @order_form %>
</div>

app/views/layouts/_user_dropdown.html.erb
<div class="btn-group pull-right">
	<% if @current_user %>
		<a class="btn dropdown-toggle text-on-yellow-bg" data-toggle="dropdown" href="#">
			<i class="icon-user"></i> <%= @current_user.name %>
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
			<li><%= link_to "用户信息", user_path(@current_user) %></li>
			<li class="divider"></li>
			<li><%= link_to "退出", "/users/signout" %></li>
		</ul>
	<% else %>
		<a class="btn dropdown-toggle text-on-yellow-bg" href="/users/login">
			<i class="icon-user"></i> 登录 / 登记
		</a>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><%= content_for?(:title) ? "#{app_name}美食外卖 - 妈妈也来外婆家蹭饭吃呢～" : "Takeout" %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="还有比妈妈做的饭更香的地方吗？那……只有外婆家了！">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<%= csrf_meta_tags %>
		<%= stylesheet "application", :media => "all" %>
		<%= yield(:stylesheet) %>
		<%= javascript_include_tag "application" %>
		<%= yield(:javascript) %>
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="shortcut icon" href="/favicon.ico">
		<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
	</head>

	<body>
		<div id="universe">
			<div class="container-fluid">
				<div class="navbar navbar-fixed-top">
					<div class="navbar-inner">
							<div class="container-fluid">
							<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</a>
							<%= link_to(app_name, root_path, :class => "brand") %>
							<%= render 'layouts/user_dropdown' %>
							<%= render 'layouts/navbar' %>
						</div>
					</div>
				</div>
			</div>

			<div class="container-fluid">
				<div class="row-fluid">
					<div class="span9">
						<%= display_flash_message %>
						<%= yield %>
					</div><!--/span-->
					<div class="span3"><%= render 'layouts/sidebar' %></div>
				</div><!--/row-->

				<footer id="footer">
					<p><%= app_name %> &copy;  2012</p>
				</footer>

			</div><!--/.fluid-container-->
			

		</div>
	</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><%= content_for?(:title) ? "#{app_name}美食外卖 - 妈妈也来外婆家蹭饭吃呢～" : "Takeout" %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="还有比妈妈做的饭更香的地方吗？那……只有外婆家了！">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<%= csrf_meta_tags %>
		<%= stylesheet "application", :media => "all" %>
		<%= yield(:stylesheet) %>
		<%= javascript_include_tag "application" %>
		<%= yield(:javascript) %>
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="shortcut icon" href="/favicon.ico">
		<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
	</head>

	<body>
		<div id="login">
			<div id="login-form">
				<form action="/users/signin" method="post">
					<div class="close" id="login-close">×</div>
					<input id="tel" type="password" name="tel" class="input-medium search-query" placeholder="输入手机号">
					<button id="login-submit" class="btn">登录 / 登记</button>
				</form>
			</div>
		</div>
		
		<script type="text/javascript">
			
		// Check login

			// init
			$('#login-form input').focus()

			// click events

			$('#login-close').click(function(){
				history.back()
			})

			$('#login-submit').click(function(){
				if ($('#tel').attr('value')==='') {
					alert('亲你忘了输入')
					return false
				}else {
					return true
				}
			})
		</script>
	</body>
</html>